on:
  label:
    types: [created,deleted,edited]
  push:
    branches:
      - main
    paths:
      - '.github/labels.json'
name: Create Default Labels
jobs:
  labels:
    name: DefaultLabelsActions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - uses: lannonbr/issue-label-manager-action@7890981d0e8f2922211a7fe2c391c53cb3037cb4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
